name: Push_to_hub

on:
  # push:
  #   branches:
  #     - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

env:
  DOCKER_FILE_PATH: .
  IMAGE_NAME: hello-world-nginx
  DEST_IMAGE_NAME: hello-world-nginx
  REGISTRY_URL: hanralatalliard/hello-world-nginx
  TAG_NAME: latest
  HUB_USERNAME: ${{secrets.HUB_USERNAME}}
  HUB_PASSWORD: ${{secrets.HUB_PASSWORD}}


jobs:
  Publish_the_docker:
    runs-on: ubuntu-latest

    steps:
    - name: Accessing the repository
      uses: actions/checkout@v3
    - name: Build the docker
      run: |
        sudo docker build -t ${{env.IMAGE_NAME}}:${{env.TAG_NAME}} ${{env.DOCKER_FILE_PATH}}
    - name: Logging into docker hub
      run: |
        echo "${{secrets.DOCKER_HUB_PASSWORD_HANRA}}" | docker login --username=${{secrets.DOCKERHUB_USERNAME_HANRA}}
    - name: Preparing image for publishing
      run: |
        sudo docker tag ${{env.IMAGE_NAME}}:${{env.TAG_NAME}} ${{env.REGISTRY_URL}}:${{env.TAG_NAME}}
    - name: Publishing image
      run: |
        sudo docker push ${{env.REGISTRY_URL}}:${{env.TAG_NAME}}
